#!/bin/bash
# A mock version of SGE qstat. Always returns a table with output the same as
# `qstat -s pr`.

sleep 2;

echo "job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
000001 0.50038 test_job.a test_user     r     09/29/2020 12:00:00 all.q@node100           1
000002 0.50038 test_job.b test_user     r     09/29/2020 12:00:00 all.q@node101           1
000003 0.50038 test_job.c test_user     r     09/29/2020 12:00:00 all.q@node102           1
"